### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by desbarmitar** [solero/dash#3]
I alredy config the Houdini-Asyncio in Xampp.
The Dash tutorial is only to nginx. Can you do a tutorial to config in Xampp?

**Comment by Zaseth** [comment]
@desbarmitar xampp uses apache. You could download nginx for windows and continue the tutorial as is.

**Comment by desbarmitar** [comment]
Thanks

**Comment by desbarmitar** [comment]
I can't configure nginx, how do I do it?

**Comment by rsakeys** [comment]
This issue is not directly related to Dash therefore you should not be opening an issue about this here. 

You can try joining our [Discord](https://discord.gg/G3N2t5q) for further support, however i'm going to close this issue as it is not an issue with Dash nor a place to be asking for support with nginx.
